### ISSUE TITLE
Security audit error: The security section of the operation 'post' contains and empty array

### ISSUE THREAD

**Issue by karelhusa** [42Crunch/intellij-openapi-editor#36]
I have an operation to get a security token, thus is not protected:

`  /token:
    post:
      summary: Get access token
      tags:
        - Security
      operationId: getToken
      security: []
      description: | 
        Get access token for protected API operations.`

42Crunch security audit gives me an error: The security section of the operation 'post' contains an empty array. Though, such a declaration is valid, as per https://swagger.io/docs/specification/authentication/. 

This operation is intentionally unsecured. Shouldn't be then treated as OK? Or, what kind of OpenAPi setup the security audit expects?

**Comment by anthony-42crunch** [comment]
Its flagged as a security issue in case the security scheme was unintentionally omitted.

You can flag it as intentional for a given operation using the extension:

`x-42c-accept-empty-security: true`

More information [here](https://docs.42crunch.com/latest/content/tasks/audit_api_security.htm#Allow).
